- name: Play Ping on all targets
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Define List
      set_fact:
        mylist: 
          - 1
          - 2
          - 3
    - name: with_items exampel 
      debug:
        msg: "{{ myplaybook_example_item }}"
      with_items: "{{ mylist }}"
      loop_control:
        loop_var: "myplaybook_example_item"
